language: rust
os:
    - linux
env:
    global:
        - secure: SZm54bw2/OBIjALwGC7uOcmadi/fTir8ag69OJMhZu3aWzX2bgtAeHfthBeV2dD7TkZBrWBAp4625LvEi1Bq/c79UrRyg4xTK8qgMhdHQKG5docr3Gfn8bIM/VbVYYh+vJY0jSwC/ADoZm/YNmFynaYOhp4P33N7Xvt55dpCsLM=
script:
    - cargo build -v
    - cargo test  -v
    - cargo doc   -v
after_script:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
